### PR TITLE
Cff zenodo files

### PR DESCRIPTION
**Pull request by jspaaks**

### CODE REVIEW

**Comment by jspaaks** [comment]
Hi @meiertgrootes 
Can you review my changes in the commits and then generate a ``.zenodo.json`` file? An easy way to do so is to use [the online version of ``cffconvert``](https://us-central1-cffconvert.cloudfunctions.net/cffconvert). 

You can point it to this repo using URL query parameters, like so https://us-central1-cffconvert.cloudfunctions.net/cffconvert?url=https://github.com/ADAH-EviDENce/evidence/tree/CFF_zenodo_files&outputformat=zenodo&ignore_suspect_keys

**Comment by meiertgrootes** [comment]
all commits accepted. .zenodo.json generated with cffconvert from PyPI. @jspaaks ready for review

**Comment by meiertgrootes** [comment]
can be merged as far as I am concerned, if you are happy with it @jspaaks. What is customary in GT w.r.t who will perform the merge?

**Review by fdiblen — APPROVED** [review]
Dankjewel!
:confetti_ball:

**Comment by jspaaks** [comment]
Hi @meiertgrootes, GitHub won't let me approve the PR, since I created it (of off your branch). But it's good to go. In GT, we (sometimes) request reviewers, and reviewers can assign themselves. After approval, the PR creator merges. So technically that's me, but please go ahead and do it yourself. After merge, don't forget to clean up any unused branches that you own.

**Pull request merged**
