### PR TITLE
fixes #117

### LINKED ISSUE #117: UI expects doc2vec.json but only corpus-vectors.json present
This bug only affects users making use of an own corpus. initial fix has been tested and will be implemented shortly

### PR DESCRIPTION
**Pull request by meiertgrootes**
Modified start.sh in ui/ to use corpus-vectors.json instead of doc2vec.json. Removed/replaced doc2vec.json in demo and getuigenverhalen. Tested ingestion of user corpus, and correct behaviour of demo and getuigenverhalen experiments.

### CODE REVIEW

**Comment by meiertgrootes** [comment]
Hi @sverhoeven,

sorry to bug you. Last bug fixing PR(s). Shouldn't cost you much time, I hope

**Review by sverhoeven — CHANGES_REQUESTED** [review]
experiments/demo/corpus-vectors.json is missing.

Could you add it again?

**Comment by meiertgrootes** [comment]
@sverhoeven Is it missing? I see it both in demo and in getuigenverhalen. Both here on GitHub in the file browser, as well as when I do a fresh clone of the repo to my local system and check there. Can you please verify that it is missing? Thanks!

**Review by sverhoeven — APPROVED** [review]
Sorry in the [files changed view](https://github.com/ADAH-EviDENce/evidence/pull/118/files) you did a rename and delete, I thought you forgot to add the file, but it is already there from an earlier commit.

**Pull request merged**
