### PR TITLE
added fair software badges

### PR DESCRIPTION
**Pull request by jspaaks**
Refs #10 (fair-software.nl badges)

### CODE REVIEW

**Review by fdiblen — CHANGES_REQUESTED** [review]
FAIR enough!

Could you please also add the badges of the new workflows?

**Comment by jspaaks** [comment]
> Could you please also add the badges of the new workflows?

I could, but I don't want to make that part of this PR. Applying my two simple rules of merging:
1. Does the PR make things better (Yes)
1. Does the PR break existing functionality? (No)

means that this can be merged. 

If we strive to "finish" every PR, you end up with a long list of PRs, which is a hassle later on, and leads to disappointments on the contributor's side.

**Comment by fdiblen** [comment]
> > Could you please also add the badges of the new workflows?
> 
> I could, but I don't want to make that part of this PR. Applying my two simple rules of merging:
> 
> 1. Does the PR make things better (Yes)
> 2. Does the PR break existing functionality? (No)
> 
> means that this can be merged.
> 
> If we strive to "finish" every PR, you end up with a long list of PRs, which is a hassle later on, and leads to disappointments on the contributor's side.

I will add the badge in the workflow PR.

**Review by fdiblen — APPROVED** [review]
Looks good.
:badminton:

**Pull request merged**
