### PR TITLE
Added schematic diagram of initial state of tool

### PR DESCRIPTION
**Pull request by meiertgrootes**
Initial schematic diagram of framework and ui as before commencement of work

### CODE REVIEW

**Review by jspaaks — APPROVED** [review]

**Comment by jspaaks** [comment]
I added it to the readme.

**Review by fdiblen — APPROVED** [review]
:performing_arts:

**Review by fdiblen — CHANGES_REQUESTED** [review]
@meiertgrootes Could you also add the draw.io file?
Can you also move these images to ``documentation`` folder?

**Comment by meiertgrootes** [comment]
added documentation folder and .drawio source file. Closing

**Pull request merged**
